remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [How to become a Science Communicator]
description: [Wie wird man Wissenschaftskommunikator*in? Die kurze Antwort ist: einfach anfangen.]
